workflows:
  apk:
    name: Build APK
    environment:
      node: 18
      groups:
        - expo_credentials
    scripts:
      - npm install
      - npm install -g eas-cli
      - eas build --platform android --profile preview --non-interactive --wait
    artifacts:
      - "*.apk"
